# Generated by Django 4.2 on 2023-05-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='user_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
